source ~/.shrc.sh
## git completion
if [ -f ~/.git-completion.bash ]; then
  source ~/.git-completion.bash
else
  echo "~/.git-completion.bash does not exist"
fi

PS1='\[\[\e[32m\][\u \t \[\e[32m\]\W]\[\e[0m$(__git_ps1)\]\]\$ '

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
. "$HOME/.cargo/env"
