syntax enable
"カラースキーマ
colorscheme OceanicNext
let g:solarized_termcolors=256
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set t_Co=256
set t_ut=
set updatetime=1
set visualbell t_vb=

set number
set smartindent
set expandtab
set shiftwidth=2
set showtabline=2
set tabstop=2
set ambiwidth=double
"検索時に大文字小文字を区別しない
set ic
"バックアップをとらない
set nobackup
"スワップファイルを作らない
set noswapfile 
"入力中のコマンドを表示
set showcmd
"現在のモードを表示
set showmode
"コピー時にクリップボードを使用
"set clipboard=unnamedplus,autoselect
set clipboard+=unnamedplus
"対応する括弧をハイライト
set showmatch
"バックスペースの挙動
"行頭で使用した場合、前の行と連結、インデントを削除
set backspace=eol,indent,start
" カーソルラインの強調表示を有効化
"set cursorline
" ステータスラインを常に表示
set laststatus=2 
" ステータスラインの内容
set statusline=%<%F\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}
set statusline+=%{fugitive#statusline()}
set statusline+=%=%l,%c%V%8P
set statusline+=%*
" インクリメンタル検索を有効化
set incsearch
" 検索文字をハイライト
set hlsearch 

" デフォルトの文字コード
set encoding=utf-8
set fileformat=unix
" 自動エンコード
set fileencoding=utf-8
set fileencodings=utf-8,iso-2022-jp,cp932,sjis,euc-jp
 
"タブ関連
set switchbuf+=usetab,newtab"
 
au BufNewFile,BufRead *.hql setlocal filetype=hive expandtab tabstop=2 shiftwidth=2
au BufNewFile,BufRead *.py setlocal expandtab tabstop=4 shiftwidth=4
au BufNewFile,BufRead *.js setlocal expandtab tabstop=2 shiftwidth=2
au BufNewFile,BufRead *.php setlocal expandtab tabstop=4 shiftwidth=4
au BufNewFile,BufRead *.cpp setlocal expandtab tabstop=2 shiftwidth=2
au BufNewFile,BufRead *.hpp setlocal expandtab tabstop=2 shiftwidth=2
au BufNewFile,BufRead *Jenkinsfile* setf groovy
au BufNewFile,BufRead *.qgs setf xml
au BufNewFile,BufRead *.md setlocal expandtab tabstop=2 shiftwidth=2

" XMLの対応カッコ移動
source $VIMRUNTIME/macros/matchit.vim

" Plug
silent! call plug#begin('~/.vim/plugged')
Plug 'autowitch/hive.vim'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'w0rp/ale'
Plug 'othree/html5.vim'
Plug 'hail2u/vim-css3-syntax'
Plug 'gorodinskiy/vim-coloresque'
Plug 'mattn/emmet-vim'
Plug 'mattn/vim-sqlfmt'
Plug 'mhartington/oceanic-next', {'do': 'cp colors/* ~/.vim/colors/'}
Plug 'tpope/vim-surround'
Plug 'Valloric/YouCompleteMe'
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable'}
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install',
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue'] }
Plug 'mechatroner/rainbow_csv'
Plug 'tpope/vim-fugitive'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'airblade/vim-gitgutter'
Plug 'leafgarland/typescript-vim'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'tell-k/vim-autopep8'
Plug 'udalov/kotlin-vim'
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-commentary'
call plug#end()

" nerdtree
let NERDTreeShowHidden=1
nnoremap <silent><C-e> :NERDTreeToggle<CR><C-w>=

nnoremap +  <C-w>+
nnoremap -  <C-w>-
nnoremap \|  <C-w>\|
nnoremap _  <C-w>_
nnoremap =  <C-w>=
vnoremap > >gv
vnoremap < <gv

" autopep8
let g:autopep8_aggressive=1

" YouCompleteMe
let g:ycm_goto_buffer_command = 'split-or-existing-window'
let g:ycm_global_ycm_extra_conf =  $HOME . '.vim/plugged/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_path_to_python_interpreter = $HOME . '/.pyenv/shims/python'
let g:ycm_autoclose_preview_window_after_insertion = 1

nnoremap jd :rightbelow vertical YcmCompleter GoTo<CR>
nnoremap gd :YcmCompleter GetDoc<CR>
nnoremap gr :YcmCompleter GoToReferences<CR>
nnoremap gy :YcmCompleter GetType<CR>
nnoremap ref :YcmCompleter RefactorRename 

" gitgutter
let g:gitgutter_highlight_lines = 0
let g:gitgutter_max_signs = 1000

nnoremap gn :GitGutterNextHunk<CR>
nnoremap gp :GitGutterPrevHunk<CR>

" vim-markdown
let g:vim_markdown_folding_disabled = 1

" go-vim
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave = 0

" ale
let g:ale_open_list = 1
let g:ale_list_window_size = 5
let g:ale_sign_column_always = 1
let g:ale_keep_list_window_open = 1
let g:ale_loclist_msg_format = '[%linter%] %s'
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_linters = {'text': ['textlint']}
let g:ale_python_auto_pipenv = 1

nmap <silent> <C-p> :lprev<CR>
nmap <silent> <C-n> :lnext<CR>


" close a loclist when a window is closed
augroup CloseLoclistWindowGroup
  autocmd!
  autocmd QuitPre * if empty(&buftype) | lclose | endif
augroup END

" vim markdown
let g:vim_markdown_new_list_item_indent = 2
