source ~/.shrc.sh
unsetopt BG_NICE

HISTFILE=~/.zsh_history
HISTSIZE=6000000
SAVEHIST=6000000
# 他ターミナルとhisoryを共有
setopt share_history
# ヒストリーに重複を表示しない
setopt histignorealldups

autoload -Uz compinit && compinit -c
autoload -Uz colors && colors
setopt auto_pushd

setopt PROMPT_SUBST ; PS1='%F{035}[%n %* %c]%f\$$(__git_ps1 " (%s)") '

# zplug
source ~/.zplug/init.zsh

zplug "zsh-users/zsh-autosuggestions", defer:2

if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load
